[build-system]
requires = ["setuptools ~= 80.9.0", "wheel ~= 0.45.0", "setuptools_scm[toml] ~= 9.2.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/ahjo/version.py"
